# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Friendza' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Firestore'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Core', '~> 5.16.0'
pod 'GoogleAppMeasurement', '~> 5.5.0'
pod 'SDWebImage', '~>4.4.2'
pod 'JGProgressHUD', '~>2.0.3'

end
